# Generated by Django 5.2.7 on 2025-10-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(db_column="first_name", max_length=30),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
